### ISSUE TITLE
Lists of primitive types produce invalid swagger files

### ISSUE THREAD

**Issue by phile314-isska** [http4s/rho#138]
If I use lists containing primitive types in case classes, the generated Swagger documentation contains invalid references to an Int type. Example Scala Code:
<pre>
case class JsonResult(number: List[Int]) extends AutoSerializable
</pre>

Actual Swagger code:
<pre>
"definitions":{
  "JsonResult":{
    "required":["number"],
    "properties":{
      "number":{
        "type":"array",
        "items":{
          "$ref":"#/definitions/Int"
        }
      }
    },
    "description":"JsonResult"
  }
</pre>

Expected Swagger code (hand-written and untested):
<pre>
"definitions":{
  "JsonResult":{
    "required":["number"],
    "properties":{
      "number":{
        "type":"array",
        "items":{
          "type":"integer",
          "format":"int32"
        }
      }
    }
  },
  "description":"JsonResult"
}
</pre>

**Comment by phile314-isska** [comment]
I debugged this a bit, and it looks like the following code is to blame:
https://github.com/http4s/rho/blob/master/swagger/src/main/scala/org/http4s/rho/swagger/models.scala#L651-L686

I didn't debug this any further, because I don't understand what the purpose of AbstractProperty/RefProperty is.

**Comment by bryce-anderson** [comment]
Sure enough, this doesn't seem right. Its trying to refer to a more complex model, for example if it was another class, but it turns out its Int, and it didn't build a more complex model for it.

**Comment by bryce-anderson** [comment]
I think the problem is really here: https://github.com/http4s/rho/blob/master/swagger/src/main/scala/org/http4s/rho/swagger/TypeBuilder.scala#L124
When its a collection rho just assumes its a ref type and doesn't actually check. It kind of looks like the method `paramSymToProp` should be recursive in the case of a collection, but I haven't tried it yet.

Please feel free to take a swing at this one if you like! I'm happy to provide guidance but I don't know if I'll get to it this week or not.
