### ISSUE TITLE
Raw Ok[Task[String]] fails

### ISSUE THREAD

**Issue by reactormonk** [http4s/rho#173]
In ammonite:

    import $ivy.`org.http4s::rho-swagger:0.16.0a` 
    import org.http4s.rho._, scalaz.concurrent.Task 
    new RhoService { GET / "foo" |>> { Ok[Task[String]](???) } } 
    
fails with

    cmd2.sc:1: diverging implicit expansion for type org.http4s.rho.bits.HListToFunc[shapeless.HNil,scalaz.concurrent.Task[this.Ok.T[scalaz.concurrent.Task[String]]]]
    starting with method taskEncoder in trait EntityEncoderInstances
    val res2 = new RhoService { GET / "foo" |>> { Ok[Task[String]](???) } }
    
WA: `task.map(OK)`

**Comment by bryce-anderson** [comment]
We've had numerous problems with implicits, including a [blocker that prohibited using scalac >= 2.11.8](https://github.com/http4s/rho/issues/136).
I don't have a quick solution other than the workaround you have. Unfortunately most of the magic of rho is due to fancy implicit resolution tricks, but we may have maxed out that credit card.

**Comment by reactormonk** [comment]
I forgot to mention - if you call parts of the expression beforehand with `implicitly`, it compiles.

**Comment by zarthross** [comment]
As of http4s 0.19  `EntityEncoder` will be pure, so there won't be an `EntityEncoder[Task[String]]`.  

You should use `foo.flatMap(Ok(_))` going forward.
