### ISSUE TITLE
is it possible to compose Rho services?

### ISSUE THREAD

**Issue by refried** [http4s/rho#67]
I naively tried to use `.toService.orElse`, but I suppose `append` or `__tree` need to come into play.

I'm guessing this isn't currently supported (after all, we're only at 0.4), but that it could be without too much trouble.  Is there anything you can think of that I should specifically avoid if I wanted to implement this?

**Comment by bryce-anderson** [comment]
This is essentially a duplication of https://github.com/http4s/rho/issues/48, which must mean its not a problem only I think about. Because the http4s service model is just a function, I don't think there will be any way to compose them once they are a ```HttpService``` and maintain the swagger docs. One simple method would be to stack traits, but that isn't really in the spirit of http4s. 

Lets me the discussion to #48, if you dont mind.
