### ISSUE TITLE
how does rho handle form data in the post

### ISSUE THREAD

**Issue by ShengC** [http4s/rho#88]
Obviously `param` only supports parameter in the restful url. 

    POST / "test" +? param[Option[String]]("data") |>> { (data: Option[String]) =>    
      Ok(s"Got ${data.getOrElse("nothing")}\n")
    }

    curl -X POST http://localhost:8085/test?data=parameter
    Got parameter
    
    curl -X POST http://localhost:8085/test --data "data=form"
    Got nothing

The entity body is abstracted as a `scalaz.stream.Process` in `org.http4s.Request`, so I am not even sure how it is possible to have something similar to `Spray` to handle parameter and form data in the route, something like this.

    post { (parameter('data.as[Option[String]]) | formField('data.as[Option[String]])) { complete(s"got ${data.getOrElse("nothing")}\n") } }

P.S. I believe the dsl project has the similar issue - it does not offer ability of handling "pattern matching" form fields in the entity body.

**Comment by bryce-anderson** [comment]
You're right, because the body is modelled as a `Process` its difficult to mix and match between the other messages parameters which are all synchronous.
Just in case you haven't found it, see [`UrlForm`](https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/UrlForm.scala) for how to decode a form body.

**Comment by ShengC** [comment]
I think it makes sense to model entity body in Response as a Procross, but
how many benefits does it bring along by doing the same for Request ? As it
cannot abstract the match of form data in the route, it kills lots of
useful patterns.

**Comment by bryce-anderson** [comment]
I think it makes a lot of sense to model the body of the `Request` as an asynchronous construct: otherwise we run the risk of OOM problems if someone posts anything large. The pattern matching stuff etc is all really a DSL problem: there is no reason we can't lift non-body stuff into the asynchronous context and perform the matching after processing the body. As it stands it just isn't that way. I'm interested in improvements if you have some ideas.

For the record, I don't think its technically possible with the core-dsl without blocking considering how `PartialFuction` works.

**Comment by ShengC** [comment]
AFAIK, there is no RFC limiting the length of restful url length. This
might sound ridiculous, but technically speaking,  client can still cause
the OOM in the server with a Curl GET, so long as the server itself does
not address the unbounded url itself. My point being, for the sake of
resource safety, the server should either consider using a `lazy` kind of
data structure for all the edge cases that might happen in real situation,
no matter how likely/unlikely they could be. Otherwise, using a more
pragmatic approach, it can place a limit check on user's input, and more
focus on offering the ability of matching and validating the input in the
route DSL. I think for the average user, usability of DSL might be more
important than the performance and alike of the server itself. Assuming
someone wants to create a form, and based on form's inputs, he wants to run
some value validations and type check on the server side, and only renders
the results if these tests pass. A simple application as trivial as this is
would require insane amount of boilerplates to write the DSL, and
experience like this could easily send him in search for a less optimized,
but more user-friendly alternative.

I have not entirely gone through the codebase of rho, but so long as there
is a way to parse the entity body similar other pieces in the Request
(either lift non-body stuff into async context, or run the body `Process`
to form a string), most of the code and methods for parameters can be
reused for the form fields.

**Comment by bryce-anderson** [comment]
While the request line and headers do not have a RFC specified limit, they are also limited by the http4s backends to avoid OOM DDOS attacks. The blaze backend currently limits the request line to 2KB and all the headers to 40KB. Right now we are using the default constructor of the `Http1ServerParser` class but the defaults can be found [here](https://github.com/http4s/blaze/blob/master/http/src/main/java/org/http4s/blaze/http/http_parser/Http1ServerParser.java). At some point those settings should probably be exposed to the user in http4s...

I'm sympathetic to your use case of checking the request POST parameters of a form submission. I don't see a problem of using the validation tools in the route action though I can think of existing constructs for that such as the FP tools in scalaz.

One thing that does come to mind is making a middleware that will lift a `Url-Form` encoded body into the `Request` parameters. That would let you do exactly what you want to do and might be generally useful.

**Comment by ShengC** [comment]
@bryce-anderson Thanks for the advice... for now I will try lifting a `url-form` encoded body into the `Request` parameters, but since request line is limited to 2KB, I don't think this should by any means let run in production. I know there is probably a dozen of ways to run validation against fields in the method body, but that sort of prevents the code reuse and composition.... I still think though a synchronized request should not be suggested, but as a framework, user should be able to explore possibility of using it _at_ _their_ _own_ _risk_

On a separate note, I know this project is heavily focused on leveraging existing Scalaz stack, but that kind of limits the extensibility of the framework. Taking using a `Process` to model the `Request` and `Response` entity body for example, what if somebody wants to use RxScala instead ? What worries me more is `scalaz-stream` as of today still is an immature project. It has quite a few bugs that contradict its promise of delivery. I am sure they are very smart people and their proposal to rewrite the library would probably solve all the problem once for all in the future. However for now as a dependency, it is just risky... My suggestion is making an interface for the entity body, and you can still use `scalaz-stream` as the default implementation, but users are allowed to choose other implementation they would prefer.

**Comment by bryce-anderson** [comment]
Check out https://github.com/http4s/http4s/pull/373. Its magic happens after the http parser so you don't need to worry about the max request line size. Please leave comments or suggestions on the PR if you feel compelled. :smile: 

I agree that scalaz is a bit risky right now, but so is this library. This library will be using whatever http4s uses so that is really a discussion for http4s. We are interested in making it usable from say, https://github.com/non/cats but the fundamental problem is that we need an async monad to use and abstracting away the monad is a bit of 'inception' so to speak. Having been dabbling in the haskell world lately, I would rather our body be of the for `Task[ByteVector]` or whatever async and effectful monad we want, but that discussion hasn't happened yet and in fact may never happen.
Ultimately, if we abstract everything away, we but the burden on the user to deal with it as well as limiting ourselves to the lowest common denominator. I think the http4s project as a whole is open to suggestions right now so please feel free to join the discussion and voice needs/opinions. 

Of course being a open source project, PRs are even better so that is probably the way to have the strongest influence on the direction of the http4s projects. :smile:

**Comment by ShengC** [comment]
@bryce-anderson that's awesome - I am, too,  thinking applying a simple `contramap` on `HttpService` to play it around first LOL but this impl looks much better, so I will just use it instead  :smile:

I am trying to persuade my team to use http4s for the new project we are working on. Used to be a Spray user for a while, and since I really disliked its forcing users to use Akka everywhere (to earn its way into typesafe), I started to explore for a lightweight alternative. I think http4s is quite promising with a much more pure FP perspective, and you and other folks as maintainers are always very responsive and willing to help :thumbsup:  I will explore the whole project more in my off hours, hopefully I can make some contributions when I hit the spot that I feel I have to :smile:

**Comment by ShengC** [comment]
Close due to `UrlFormLifter` is now released through `http4s-0.9`
